"""Learning curves, areas and the per-run register built from a run directory (manifest, episodes, groups), with
the accepted lineage across attempts and an explicit completeness check against the spec and the frozen task
pools: exact evaluation, diagnostic and training identities, not counts alone."""

import json
import pathlib
from collections import Counter, defaultdict

from pairedrl.analysis.diagnostics import luck_share_over_tasks, luck_share_pooled
from pairedrl.train.runner import (
    RunSpec,
    expected_eval_sizes,
    expected_evidence,
    identity_counts,
    load_task_splits,
    luck_share_tables_by_phase,
    read_episode_log,
    summarize_episodes,
    summarize_groups,
    task_pool_digests,
)

PERIODIC_SETS = ("clean", "noisy", "challenge")
DEFAULT_DATA_DIR = pathlib.Path(__file__).resolve().parents[3] / "data" / "tasks"


def _phase_step(phase: str) -> int | None:
    tail = phase.rsplit("step", 1)
    return int(tail[1]) if len(tail) == 2 and tail[1].isdigit() else None


def _resume_step(manifest: dict) -> int | None:
    if manifest.get("resumed_from_step") is not None:
        return int(manifest["resumed_from_step"])
    path = manifest.get("resumed_from_checkpoint")
    if path:
        tail = str(path).rstrip("/").rsplit("checkpoint-", 1)
        if len(tail) == 2 and tail[1].isdigit():
            return int(tail[1])
    return None


def _in_lineage(record: dict, cutoff: int | None) -> bool:
    """Whether a record of an earlier attempt survived the resume that followed it. Training rollouts are tagged
    with the number of completed steps when they were generated, so those at the cutoff step itself were
    regenerated by the resumed attempt; evaluations at the cutoff step preceded the checkpoint and stand."""
    if cutoff is None:
        return True
    phase = record.get("phase", "")
    step = _phase_step(phase)
    if step is None:
        return True
    return step < cutoff if phase.startswith("train:") else step <= cutoff


def load_attempts(run_dir) -> list[dict]:
    """Every attempt of a run, oldest first: archived ones from attempt<n>/ and the current one from the root."""
    run_dir = pathlib.Path(run_dir)
    attempts = []
    for d in sorted(run_dir.glob("attempt*"), key=lambda d: int(d.name[7:]) if d.name[7:].isdigit() else 0):
        if (d / "run_manifest.json").exists():
            attempts.append({"dir": d, "manifest": json.loads((d / "run_manifest.json").read_text(encoding="utf-8"))})
    attempts.append({"dir": run_dir, "manifest": json.loads((run_dir / "run_manifest.json").read_text(encoding="utf-8"))})
    return attempts


def _record_phase(record: dict, name: str) -> str:
    if name == "groups.jsonl":
        return f"train:step{record.get('step')}"
    return record.get("phase", "")


def lineage_records(attempts: list[dict], name: str) -> tuple[list[dict], dict]:
    """Records of `name` (episodes.jsonl or groups.jsonl) along the accepted checkpoint lineage. An attempt's
    records count up to the step the next attempt resumed from (the minimum over all later attempts); a phase (one
    evaluation set at one step, or one training step) that a later attempt produced again supersedes the earlier
    attempt's copy, which happens when an attempt died after its final evaluation and the relaunch repeated it.
    Returns the records and the per-attempt bookkeeping (records, superseded, cutoff, resume step)."""
    later_resumes = [_resume_step(a["manifest"]) for a in attempts[1:]]
    per_attempt = []
    bookkeeping = []
    for i, a in enumerate(attempts):
        cutoffs = [c for c in later_resumes[i:] if c is not None]
        cutoff = min(cutoffs) if cutoffs else None
        if i < len(attempts) - 1 and not cutoffs:
            cutoff = -1
        records = read_episode_log(a["dir"] / name)
        if name == "groups.jsonl":
            kept = [r for r in records if _in_lineage({"phase": _record_phase(r, name)}, cutoff)]
        else:
            kept = [r for r in records if _in_lineage(r, cutoff)]
        per_attempt.append(kept)
        bookkeeping.append({
            "attempt": a["manifest"].get("attempt"), "records": len(records), "superseded": len(records) - len(kept),
            "cutoff_step": cutoff, "resumed_from_step": _resume_step(a["manifest"]),
        })
    out = []
    for i, kept in enumerate(per_attempt):
        later_phases = {_record_phase(r, name) for later in per_attempt[i + 1:] for r in later}
        repeated = [r for r in kept if _record_phase(r, name) in later_phases]
        bookkeeping[i]["superseded"] += len(repeated)
        out.extend(r for r in kept if _record_phase(r, name) not in later_phases)
    return out, {"attempts": bookkeeping}


def periodic_curve(records: list[dict], set_name: str) -> list[dict]:
    """Points (step, n, true_success, observed_reward, recovery_success, exposed_frac, budget_exceeded_frac)
    of one periodic evaluation set, in step order."""
    by_step: dict[int, list[dict]] = defaultdict(list)
    prefix = f"eval_{set_name}:step"
    for r in records:
        phase = r.get("phase", "")
        if phase.startswith(prefix):
            by_step[_phase_step(phase)].append(r)
    points = []
    for step in sorted(by_step):
        recs = by_step[step]
        agg = summarize_episodes(recs)
        (_key, value), = agg.items()
        points.append({"step": step, "n": value["episodes"], **{k: v for k, v in value.items() if k != "episodes"}})
    return points


def area_under_curve(points: list[dict], field: str = "true_success") -> float | None:
    """Trapezoidal mean of `field` over the evaluated steps: the average level along the run, in [0, 1]."""
    if len(points) < 2:
        return None
    steps = [p["step"] for p in points]
    values = [p[field] for p in points]
    total = sum((steps[i + 1] - steps[i]) * (values[i] + values[i + 1]) / 2 for i in range(len(points) - 1))
    return total / (steps[-1] - steps[0])


def steps_to_threshold(points: list[dict], threshold: float, field: str = "true_success") -> float | None:
    """First evaluated step at which `field` reaches `threshold`, linearly interpolated; None when censored."""
    for i, p in enumerate(points):
        if p[field] >= threshold:
            if i == 0:
                return float(p["step"])
            prev = points[i - 1]
            span = p[field] - prev[field]
            frac = (threshold - prev[field]) / span if span > 0 else 1.0
            return prev["step"] + frac * (p["step"] - prev["step"])
    return None


def final_sets(records: list[dict]) -> dict:
    out = {}
    for key, agg in summarize_episodes(records).items():
        phase, condition = key.split("|", 1)
        if phase.startswith("final_"):
            out[condition.replace("eval:", "")] = {"step": _phase_step(phase), **agg}
    return out


def training_curve(records: list[dict]) -> list[dict]:
    by_step: dict[int, list[dict]] = defaultdict(list)
    for r in records:
        phase = r.get("phase", "")
        if phase.startswith("train:step"):
            by_step[_phase_step(phase)].append(r)
    points = []
    for step in sorted(by_step):
        recs = by_step[step]
        n = len(recs)
        points.append({
            "step": step, "n": n,
            "true_success": sum(r["true_success"] for r in recs) / n,
            "observed_reward": sum(r["observed_reward"] for r in recs) / n,
            "budget_exceeded_frac": sum(r["budget_exceeded"] for r in recs) / n,
            "mean_calls": sum(r["calls"] for r in recs) / n,
        })
    return points


def luck_by_phase(records: list[dict]) -> dict:
    out = {}
    for phase, tables in luck_share_tables_by_phase(records).items():
        over = luck_share_over_tasks(tables) if tables else {"tasks": 0, "tasks_defined": 0, "lam": None}
        over["lam_pooled"] = luck_share_pooled(tables) if tables else None
        over["tables"] = len(tables)
        out[phase] = over
    return out


def step_timing_summary(timings: list[dict]) -> dict:
    if not timings:
        return {}
    seconds = [t["seconds"] for t in timings]
    gen = [t["generation_s"] for t in timings if t.get("generation_s") is not None]
    return {
        "steps": len(timings),
        "mean_step_s": sum(seconds) / len(seconds),
        "mean_generation_s": (sum(gen) / len(gen)) if gen else None,
        "mean_passes_s": ((sum(seconds) - sum(gen)) / len(gen)) if gen and len(gen) == len(seconds) else None,
        "min_step_s": min(seconds),
        "max_step_s": max(seconds),
    }


def _multiset_diff(expected: Counter, found: Counter) -> tuple[int, int]:
    return sum((expected - found).values()), sum((found - expected).values())


def _group_defects(spec: RunSpec, groups: list[dict], evidence: dict) -> list[dict]:
    """Every training step must hold groups 0 to P - 1, each on the task and schedule of its row in trainer order,
    with `num_generations` members; groups at steps outside the plan are defects too."""
    by_step: dict[int, dict[int, dict]] = defaultdict(dict)
    duplicates = []
    for g in groups:
        if g.get("group") in by_step[g.get("step")]:
            duplicates.append({"step": g.get("step"), "defect": f"group {g.get('group')} recorded twice"})
        by_step[g.get("step")][g.get("group")] = g
    defects = list(duplicates)
    planned = evidence["training"]
    for step, expected in enumerate(planned):
        found = by_step.get(step, {})
        if sorted(found) != list(range(len(expected))):
            defects.append({"step": step, "defect": f"groups {sorted(found)} instead of 0..{len(expected) - 1}"})
        for g, (task_id, schedule_seed, condition) in enumerate(expected):
            record = found.get(g)
            if record is None:
                continue
            if record.get("task_id") != task_id or int(record.get("schedule_seed", -1)) != schedule_seed or record.get("condition") != condition:
                defects.append({"step": step, "defect": f"group {g} is {record.get('task_id')}/{record.get('schedule_seed')}/{record.get('condition')}, expected {task_id}/{schedule_seed}/{condition}"})
            sizes = {len(record.get(k, [])) for k in ("true_success", "observed_reward", "advantages")}
            if sizes != {spec.num_generations}:
                defects.append({"step": step, "defect": f"group {g} has member counts {sorted(sizes)}, expected {spec.num_generations}"})
    for step in sorted((s for s in by_step if not isinstance(s, int) or s < 0 or s >= len(planned)), key=str):
        defects.append({"step": step, "defect": f"{len(by_step[step])} groups at a step outside the plan"})
    return defects


def completeness(spec: RunSpec, records: list[dict], groups: list[dict], luck: dict, evidence: dict, pools: dict) -> dict:
    """What a complete run must contain, from the spec and the frozen pools, against what the lineage holds: every
    periodic set at every registered step and every final set at the final step with exactly the expected
    (task, schedule, condition) records, every diagnostic step with the frozen diagnostic tasks under K schedules
    and M samples each, every training step with its groups and rollouts in trainer order, no phase outside that
    plan, exact totals, and pool files whose hashes match the manifest. Job status says the process ended; this
    says the evidence is whole and is the evidence the protocol asked for."""
    sizes = expected_eval_sizes(spec)
    by_phase: dict[str, list[dict]] = defaultdict(list)
    for r in records:
        by_phase[r.get("phase", "")].append(r)
    missing = []
    identity = []
    expected_phases = set()

    def check(phase: str, expected: Counter, label: str, step: int, expected_n: int) -> None:
        expected_phases.add(phase)
        found = identity_counts(by_phase.get(phase, []))
        n_found = sum(found.values())
        if n_found != expected_n:
            missing.append({"set": label, "step": step, "found": n_found, "expected": expected_n})
        miss, extra = _multiset_diff(expected, found)
        if miss or extra:
            identity.append({"phase": phase, "missing": miss, "extra": extra})

    for step in evidence["periodic_steps"]:
        for name, expected in evidence["periodic"].items():
            check(f"eval_{name}:step{step}", expected, f"eval_{name}", step, sizes["periodic"][name])
    for name, expected in evidence["final"].items():
        check(f"final_{name}:step{evidence['final_step']}", expected, f"final_{name}", evidence["final_step"], sizes["final"][name])
    diag_steps = evidence["diagnostic_steps"]
    diag_missing = []
    for step in diag_steps:
        phase = f"diag:step{step}"
        check(phase, evidence["diagnostic"], "diag", step, sum(evidence["diagnostic"].values()))
        info = luck.get(phase)
        if info is None or info.get("defect"):
            diag_missing.append({"phase": phase, "found": (info or {}).get("tasks", 0), "defect": (info or {}).get("defect", "absent")})
    for step, expected_groups in enumerate(evidence["training"]):
        expected = Counter()
        for key in expected_groups:
            expected[key] += spec.num_generations
        check(f"train:step{step}", expected, "train", step, len(expected_groups) * spec.num_generations)
    unexpected = {phase: len(recs) for phase, recs in sorted(by_phase.items()) if phase not in expected_phases}
    group_defects = _group_defects(spec, groups, evidence)
    expected_groups_n = sum(len(g) for g in evidence["training"])
    expected_rollouts = expected_groups_n * spec.num_generations
    training_rollouts = sum(1 for r in records if r.get("phase", "").startswith("train"))
    expected_diag = sum(evidence["diagnostic"].values()) * len(diag_steps)
    pools_match = bool(pools) and all(v.get("match") for v in pools.values())
    out = {
        "periodic_steps_expected": list(evidence["periodic_steps"]),
        "periodic_and_final_missing": missing,
        "identity_defects": identity,
        "unexpected_phases": unexpected,
        "final_step_expected": evidence["final_step"],
        "diagnostic_steps_expected": list(diag_steps),
        "diagnostic_tasks": evidence["diagnostic_tasks"],
        "diagnostic_missing": diag_missing,
        "group_defects": group_defects,
        "training_groups_expected": expected_groups_n,
        "training_groups_found": len(groups),
        "training_rollouts_expected": expected_rollouts,
        "training_rollouts_found": training_rollouts,
        "episodes_expected": (
            sum(sizes["periodic"].values()) * len(evidence["periodic_steps"])
            + sum(sizes["final"][name] for name in evidence["final"])
            + expected_diag
            + expected_rollouts
        ),
        "episodes_found": len(records),
        "task_pools": {name: {"count": v["count"], "sha256": v["sha256"], "match": v["match"]} for name, v in pools.items()},
        "task_pools_match": pools_match,
    }
    out["totals_match"] = out["episodes_found"] == out["episodes_expected"] and len(groups) == expected_groups_n
    out["complete"] = (
        not missing and not identity and not unexpected and not diag_missing and not group_defects
        and out["totals_match"] and pools_match
    )
    return out


def luck_by_phase_strict(records: list[dict], spec: RunSpec) -> dict:
    """Luck share per diagnostic phase with the K x M cardinality enforced per task; a phase whose tables are not
    all K x M is reported with its defect rather than silently averaged."""
    out = luck_by_phase(records)
    for phase in out:
        phase_records = [r for r in records if r.get("condition") == "diag" and r.get("phase") == phase]
        try:
            luck_share_tables_by_phase(phase_records, schedules=spec.diagnostic_schedules, samples=spec.diagnostic_samples)
        except ValueError as e:
            out[phase]["defect"] = str(e)
    return out


def checkpoint_inventory(run_dir, spec: RunSpec) -> dict | None:
    """Which trainer checkpoints exist and are complete (adapter with config, optimizer, scheduler, RNG state and a
    parseable trainer_state.json at the directory's step), when the weights were collected (None otherwise)."""
    from pairedrl.ops.job import ADAPTER_CONFIG, checkpoint_defects, list_checkpoints

    trainer = pathlib.Path(run_dir) / "trainer"
    if not trainer.exists():
        return None
    complete, incomplete = list_checkpoints(trainer)
    expected = [] if spec.eval_only else list(range(spec.checkpoint_steps, spec.steps + 1, spec.checkpoint_steps))
    found = [int(c.name.split("-")[1]) for c in complete]
    adapter_final = pathlib.Path(run_dir) / "adapter_final"
    return {
        "expected": expected,
        "complete": found,
        "incomplete": [c.name for c in incomplete],
        "defects": {c.name: checkpoint_defects(c) for c in incomplete},
        "missing": [s for s in expected if s not in found],
        "adapter_final": (adapter_final / "adapter_model.safetensors").exists() and (adapter_final / ADAPTER_CONFIG).exists(),
    }


def attempt_consistency(attempts: list[dict]) -> dict:
    """Whether every attempt of a run used the same code, model snapshot and task pools: the code commit may only
    change when the later attempt's spec names the earlier commit in `relaunch_from_commit` (an infrastructure-only
    change recorded in docs/DEVIATIONS.md); the model commit hash and the pool hashes may never change."""
    from pairedrl.ops.job import commit_named, pool_hashes

    commits = [a["manifest"].get("deployed_commit") or a["manifest"].get("git_commit") for a in attempts]
    changes = []
    for i in range(1, len(attempts)):
        if commits[i] != commits[i - 1]:
            named = (attempts[i]["manifest"].get("spec") or {}).get("relaunch_from_commit")
            changes.append({"attempt": attempts[i]["manifest"].get("attempt"), "from": commits[i - 1], "to": commits[i],
                            "acknowledged": commit_named(named, commits[i - 1])})
    models = [a["manifest"].get("model_commit_hash") for a in attempts]
    known_models = {m for m in models if m}
    pools = [pool_hashes(a["manifest"].get("task_pools")) for a in attempts]
    known_pools = [p for p in pools if p]
    return {
        "commits": commits,
        "commit_changes": changes,
        "commits_consistent": all(c["acknowledged"] for c in changes),
        "model_commit_hashes": models,
        "model_consistent": len(known_models) <= 1,
        "task_pools_consistent": all(p == known_pools[0] for p in known_pools),
    }


def run_register(run_dir, threshold: float | None = None, data_dir=None) -> dict:
    """Everything the paper reads from one run: spec facts, periodic curves with areas, final sets, luck share
    per checkpoint, training-group totals, training curve, timing summary, the attempt lineage, completeness
    against the frozen pools under `data_dir` (the repository's data/tasks by default) and attempt consistency."""
    run_dir = pathlib.Path(run_dir)
    data_dir = pathlib.Path(data_dir) if data_dir is not None else DEFAULT_DATA_DIR
    attempts = load_attempts(run_dir)
    manifest = attempts[-1]["manifest"]
    records, episode_lineage = lineage_records(attempts, "episodes.jsonl")
    groups, group_lineage = lineage_records(attempts, "groups.jsonl")
    spec = manifest["spec"]
    run_spec = RunSpec.from_dict(spec)
    curves = {name: periodic_curve(records, name) for name in PERIODIC_SETS}
    luck = luck_by_phase_strict(records, run_spec)
    evidence = expected_evidence(run_spec, load_task_splits(data_dir))
    pools = task_pool_digests(data_dir)
    entry = {
        "run_id": manifest["run_id"],
        "provider": manifest.get("provider", "modal"),
        "status": manifest.get("status"),
        "attempt": manifest.get("attempt"),
        "attempts": [
            {
                "attempt": a["manifest"].get("attempt"), "status": a["manifest"].get("status"),
                "git_commit": a["manifest"].get("git_commit"), "deployed_commit": a["manifest"].get("deployed_commit"),
                "model_commit_hash": a["manifest"].get("model_commit_hash"), "resumed_from_step": _resume_step(a["manifest"]),
                "wall_time_s": a["manifest"].get("wall_time_s"), "estimated_cost_usd": a["manifest"].get("estimated_cost_usd"),
                "error": a["manifest"].get("error"),
            }
            for a in attempts
        ],
        "attempt_consistency": attempt_consistency(attempts),
        "total_wall_time_s": sum((a["manifest"].get("wall_time_s") or 0) for a in attempts),
        "total_estimated_cost_usd": round(sum((a["manifest"].get("estimated_cost_usd") or 0) for a in attempts), 2),
        "lineage": {"episodes": episode_lineage["attempts"], "groups": group_lineage["attempts"]},
        "git_commit": manifest.get("git_commit"),
        "condition": spec.get("condition"),
        "arm": spec.get("arm"),
        "seed": spec.get("seed"),
        "p": spec.get("p"),
        "q": spec.get("q"),
        "fault_weights": spec.get("fault_weights"),
        "steps": spec.get("steps"),
        "prompts_per_step": spec.get("prompts_per_step"),
        "num_generations": spec.get("num_generations"),
        "scale_rewards": spec.get("scale_rewards"),
        "loss_type": spec.get("loss_type"),
        "wall_time_s": manifest.get("wall_time_s"),
        "estimated_cost_usd": manifest.get("estimated_cost_usd"),
        "peak_mem_gb": manifest.get("peak_mem_gb"),
        "versions": manifest.get("versions"),
        "episodes": len(records),
        "curves": curves,
        "auc": {name: area_under_curve(points) for name, points in curves.items()},
        "final": final_sets(records),
        "luck_share": luck,
        "training_groups": summarize_groups(groups) if groups else {},
        "training_curve": training_curve(records),
        "timing": step_timing_summary(manifest.get("step_timings", [])),
        "eval_timings": manifest.get("eval_timings", []),
        "completeness": completeness(run_spec, records, groups, luck, evidence, pools),
        "checkpoints": checkpoint_inventory(run_dir, run_spec),
    }
    if threshold is not None:
        entry["threshold"] = threshold
        entry["steps_to_threshold"] = steps_to_threshold(curves["noisy"], threshold) if curves["noisy"] else None
    return entry


def format_run(entry: dict) -> str:
    lines = [
        (
            f"{entry['run_id']} ({entry['condition']} {entry['arm']} seed {entry['seed']}, {entry['provider']}): "
            f"status {entry['status']}, {entry['episodes']} episodes, {entry['wall_time_s']} s, "
            f"est {entry['estimated_cost_usd']} USD"
        )
    ]
    for name in PERIODIC_SETS:
        points = entry["curves"].get(name, [])
        if points:
            values = " ".join(f"{p['step']}:{p['true_success']:.3f}" for p in points)
            auc = entry["auc"].get(name)
            lines.append(f"  {name:10s} {values}  auc={auc:.3f}" if auc is not None else f"  {name:10s} {values}")
    for name, agg in sorted(entry["final"].items()):
        rec = agg["recovery_success"]
        lines.append(
            f"  final {name:14s} true={agg['true_success']:.3f} recovery={'n/a' if rec is None else f'{rec:.3f}'} "
            f"exposed={agg['exposed_frac']:.2f} calls={agg['mean_calls']:.1f} budget_exceeded={agg['budget_exceeded_frac']:.2f}"
        )
    for phase, luck in sorted(entry["luck_share"].items(), key=lambda kv: _phase_step(kv[0]) or 0):
        lam, pooled = luck.get("lam"), luck.get("lam_pooled")
        lines.append(
            f"  luck share {phase}: lam={'n/a' if lam is None else f'{lam:.3f}'} "
            f"pooled={'n/a' if pooled is None else f'{pooled:.3f}'} over {luck.get('tasks_defined')} of {luck.get('tasks')} tasks"
        )
    for condition, g in sorted(entry["training_groups"].items()):
        spurious = g["spurious_among_all_correct"]
        lines.append(
            f"  groups {condition}: {g['groups']} groups, zero-variance {g['zero_variance_frac']:.3f}, "
            f"all-correct {g['all_correct_groups']}, spurious among all-correct "
            f"{'n/a' if spurious is None else f'{spurious:.3f}'}"
        )
    timing = entry.get("timing") or {}
    if timing:
        gen, passes = timing.get("mean_generation_s"), timing.get("mean_passes_s")
        lines.append(
            f"  timing: {timing['steps']} steps, mean {timing['mean_step_s']:.1f} s "
            f"(generation {'n/a' if gen is None else f'{gen:.1f}'} s, passes {'n/a' if passes is None else f'{passes:.1f}'} s)"
        )
    if "threshold" in entry:
        stt = entry["steps_to_threshold"]
        lines.append(f"  threshold {entry['threshold']:.3f}: steps to threshold {'censored' if stt is None else f'{stt:.1f}'}")
    comp = entry.get("completeness") or {}
    if comp:
        lines.append(
            f"  completeness: {'COMPLETE' if comp['complete'] else 'INCOMPLETE'}; episodes {comp['episodes_found']}/{comp['episodes_expected']}, "
            f"groups {comp['training_groups_found']}/{comp['training_groups_expected']}, "
            f"missing sets {len(comp['periodic_and_final_missing'])}, identity defects {len(comp['identity_defects'])}, "
            f"unexpected phases {len(comp['unexpected_phases'])}, diagnostic defects {len(comp['diagnostic_missing'])}, "
            f"group defects {len(comp['group_defects'])}, pools {'match' if comp['task_pools_match'] else 'MISMATCH'}; "
            f"attempts {len(entry.get('attempts', []))}, total {entry.get('total_wall_time_s')} s, est {entry.get('total_estimated_cost_usd')} USD"
        )
        for m in comp["periodic_and_final_missing"][:6]:
            lines.append(f"    missing {m['set']} step {m['step']}: {m['found']} of {m['expected']}")
        for m in comp["identity_defects"][:6]:
            lines.append(f"    identity {m['phase']}: {m['missing']} expected records absent, {m['extra']} unexpected")
        for phase, n in list(comp["unexpected_phases"].items())[:6]:
            lines.append(f"    unexpected {phase}: {n} records")
        for m in comp["diagnostic_missing"][:3]:
            lines.append(f"    diagnostic {m['phase']}: {m['defect']}")
        for m in comp["group_defects"][:6]:
            lines.append(f"    groups step {m['step']}: {m['defect']}")
    consistency = entry.get("attempt_consistency") or {}
    if consistency:
        lines.append(
            f"  attempts: commits {consistency['commits']} ({'consistent' if consistency['commits_consistent'] else 'UNACKNOWLEDGED CHANGE'}), "
            f"model {'consistent' if consistency['model_consistent'] else 'CHANGED'}, "
            f"pools {'consistent' if consistency['task_pools_consistent'] else 'CHANGED'}"
        )
    ck = entry.get("checkpoints")
    if ck is not None:
        lines.append(
            f"  checkpoints: complete {ck['complete']}, missing {ck['missing']}, incomplete {ck['incomplete']}, "
            f"adapter_final {ck['adapter_final']}"
        )
        for name, defects in ck["defects"].items():
            lines.append(f"    {name}: {', '.join(defects)}")
    return "\n".join(lines)
