"""Learning curves, areas and the per-run register built from a run directory (manifest, episodes, groups), with
the accepted lineage across attempts and an explicit completeness check against the spec."""

import json
import pathlib
from collections import defaultdict

from pairedrl.analysis.diagnostics import luck_share_over_tasks, luck_share_pooled
from pairedrl.train.runner import (
    RunSpec,
    expected_eval_sizes,
    luck_share_tables_by_phase,
    periodic_steps,
    read_episode_log,
    summarize_episodes,
    summarize_groups,
)

PERIODIC_SETS = ("clean", "noisy", "challenge")


def _phase_step(phase: str) -> int | None:
    tail = phase.rsplit("step", 1)
    return int(tail[1]) if len(tail) == 2 and tail[1].isdigit() else None


def _resume_step(manifest: dict) -> int | None:
    if manifest.get("resumed_from_step") is not None:
        return int(manifest["resumed_from_step"])
    path = manifest.get("resumed_from_checkpoint")
    if path:
        tail = str(path).rstrip("/").rsplit("checkpoint-", 1)
        if len(tail) == 2 and tail[1].isdigit():
            return int(tail[1])
    return None


def _in_lineage(record: dict, cutoff: int | None) -> bool:
    """Whether a record of an earlier attempt survived the resume that followed it. Training rollouts are tagged
    with the number of completed steps when they were generated, so those at the cutoff step itself were
    regenerated by the resumed attempt; evaluations at the cutoff step preceded the checkpoint and stand."""
    if cutoff is None:
        return True
    phase = record.get("phase", "")
    step = _phase_step(phase)
    if step is None:
        return True
    return step < cutoff if phase.startswith("train:") else step <= cutoff


def load_attempts(run_dir) -> list[dict]:
    """Every attempt of a run, oldest first: archived ones from attempt<n>/ and the current one from the root."""
    run_dir = pathlib.Path(run_dir)
    attempts = []
    for d in sorted(run_dir.glob("attempt*"), key=lambda d: int(d.name[7:]) if d.name[7:].isdigit() else 0):
        if (d / "run_manifest.json").exists():
            attempts.append({"dir": d, "manifest": json.loads((d / "run_manifest.json").read_text(encoding="utf-8"))})
    attempts.append({"dir": run_dir, "manifest": json.loads((run_dir / "run_manifest.json").read_text(encoding="utf-8"))})
    return attempts


def _record_phase(record: dict, name: str) -> str:
    if name == "groups.jsonl":
        return f"train:step{record.get('step')}"
    return record.get("phase", "")


def lineage_records(attempts: list[dict], name: str) -> tuple[list[dict], dict]:
    """Records of `name` (episodes.jsonl or groups.jsonl) along the accepted checkpoint lineage. An attempt's
    records count up to the step the next attempt resumed from (the minimum over all later attempts); a phase (one
    evaluation set at one step, or one training step) that a later attempt produced again supersedes the earlier
    attempt's copy, which happens when an attempt died after its final evaluation and the relaunch repeated it.
    Returns the records and the per-attempt bookkeeping (records, superseded, cutoff, resume step)."""
    later_resumes = [_resume_step(a["manifest"]) for a in attempts[1:]]
    per_attempt = []
    bookkeeping = []
    for i, a in enumerate(attempts):
        cutoffs = [c for c in later_resumes[i:] if c is not None]
        cutoff = min(cutoffs) if cutoffs else None
        if i < len(attempts) - 1 and not cutoffs:
            cutoff = -1
        records = read_episode_log(a["dir"] / name)
        if name == "groups.jsonl":
            kept = [r for r in records if _in_lineage({"phase": _record_phase(r, name)}, cutoff)]
        else:
            kept = [r for r in records if _in_lineage(r, cutoff)]
        per_attempt.append(kept)
        bookkeeping.append({
            "attempt": a["manifest"].get("attempt"), "records": len(records), "superseded": len(records) - len(kept),
            "cutoff_step": cutoff, "resumed_from_step": _resume_step(a["manifest"]),
        })
    out = []
    for i, kept in enumerate(per_attempt):
        later_phases = {_record_phase(r, name) for later in per_attempt[i + 1:] for r in later}
        repeated = [r for r in kept if _record_phase(r, name) in later_phases]
        bookkeeping[i]["superseded"] += len(repeated)
        out.extend(r for r in kept if _record_phase(r, name) not in later_phases)
    return out, {"attempts": bookkeeping}


def periodic_curve(records: list[dict], set_name: str) -> list[dict]:
    """Points (step, n, true_success, observed_reward, recovery_success, exposed_frac, budget_exceeded_frac)
    of one periodic evaluation set, in step order."""
    by_step: dict[int, list[dict]] = defaultdict(list)
    prefix = f"eval_{set_name}:step"
    for r in records:
        phase = r.get("phase", "")
        if phase.startswith(prefix):
            by_step[_phase_step(phase)].append(r)
    points = []
    for step in sorted(by_step):
        recs = by_step[step]
        agg = summarize_episodes(recs)
        (_key, value), = agg.items()
        points.append({"step": step, "n": value["episodes"], **{k: v for k, v in value.items() if k != "episodes"}})
    return points


def area_under_curve(points: list[dict], field: str = "true_success") -> float | None:
    """Trapezoidal mean of `field` over the evaluated steps: the average level along the run, in [0, 1]."""
    if len(points) < 2:
        return None
    steps = [p["step"] for p in points]
    values = [p[field] for p in points]
    total = sum((steps[i + 1] - steps[i]) * (values[i] + values[i + 1]) / 2 for i in range(len(points) - 1))
    return total / (steps[-1] - steps[0])


def steps_to_threshold(points: list[dict], threshold: float, field: str = "true_success") -> float | None:
    """First evaluated step at which `field` reaches `threshold`, linearly interpolated; None when censored."""
    for i, p in enumerate(points):
        if p[field] >= threshold:
            if i == 0:
                return float(p["step"])
            prev = points[i - 1]
            span = p[field] - prev[field]
            frac = (threshold - prev[field]) / span if span > 0 else 1.0
            return prev["step"] + frac * (p["step"] - prev["step"])
    return None


def final_sets(records: list[dict]) -> dict:
    out = {}
    for key, agg in summarize_episodes(records).items():
        phase, condition = key.split("|", 1)
        if phase.startswith("final_"):
            out[condition.replace("eval:", "")] = {"step": _phase_step(phase), **agg}
    return out


def training_curve(records: list[dict]) -> list[dict]:
    by_step: dict[int, list[dict]] = defaultdict(list)
    for r in records:
        phase = r.get("phase", "")
        if phase.startswith("train:step"):
            by_step[_phase_step(phase)].append(r)
    points = []
    for step in sorted(by_step):
        recs = by_step[step]
        n = len(recs)
        points.append({
            "step": step, "n": n,
            "true_success": sum(r["true_success"] for r in recs) / n,
            "observed_reward": sum(r["observed_reward"] for r in recs) / n,
            "budget_exceeded_frac": sum(r["budget_exceeded"] for r in recs) / n,
            "mean_calls": sum(r["calls"] for r in recs) / n,
        })
    return points


def luck_by_phase(records: list[dict]) -> dict:
    out = {}
    for phase, tables in luck_share_tables_by_phase(records).items():
        over = luck_share_over_tasks(tables) if tables else {"tasks": 0, "tasks_defined": 0, "lam": None}
        over["lam_pooled"] = luck_share_pooled(tables) if tables else None
        over["tables"] = len(tables)
        out[phase] = over
    return out


def step_timing_summary(timings: list[dict]) -> dict:
    if not timings:
        return {}
    seconds = [t["seconds"] for t in timings]
    gen = [t["generation_s"] for t in timings if t.get("generation_s") is not None]
    return {
        "steps": len(timings),
        "mean_step_s": sum(seconds) / len(seconds),
        "mean_generation_s": (sum(gen) / len(gen)) if gen else None,
        "mean_passes_s": ((sum(seconds) - sum(gen)) / len(gen)) if gen and len(gen) == len(seconds) else None,
        "min_step_s": min(seconds),
        "max_step_s": max(seconds),
    }


def completeness(spec: RunSpec, records: list[dict], groups: list[dict], curves: dict, luck: dict) -> dict:
    """What a complete run must contain, from the spec alone, against what the lineage holds: every periodic set
    at every registered step with its full episode count, every final set, every diagnostic phase with K x M
    samples per task, and all training groups. Job status says the process ended; this says the evidence is whole."""
    sizes = expected_eval_sizes(spec)
    missing = []
    for name, expected in sizes["periodic"].items():
        found = {p["step"]: p["n"] for p in curves.get(name, [])}
        for step in periodic_steps(spec):
            if found.get(step) != expected:
                missing.append({"set": f"eval_{name}", "step": step, "found": found.get(step, 0), "expected": expected})
    final_found = {}
    for r in records:
        phase = r.get("phase", "")
        if phase.startswith("final_"):
            final_found[phase.split(":", 1)[0][len("final_"):]] = final_found.get(phase.split(":", 1)[0][len("final_"):], 0) + 1
    if not spec.train_only:
        for name, expected in sizes["final"].items():
            if final_found.get(name, 0) != expected:
                missing.append({"set": f"final_{name}", "step": spec.steps, "found": final_found.get(name, 0), "expected": expected})
    diag_steps = [s for s in spec.diagnostic_steps if s == 0 or not spec.eval_only]
    diag_missing = []
    for step in diag_steps:
        phase = f"diag:step{step}"
        info = luck.get(phase)
        if info is None or info.get("defect"):
            diag_missing.append({"phase": phase, "found": (info or {}).get("tasks", 0), "defect": (info or {}).get("defect", "absent")})
    expected_groups = 0 if spec.eval_only else spec.steps * spec.prompts_per_step
    expected_rollouts = expected_groups * spec.num_generations
    training_rollouts = sum(1 for r in records if r.get("phase", "").startswith("train"))
    diag_tasks = max((info.get("tasks", 0) for info in luck.values()), default=0)
    expected_diag = diag_tasks * spec.diagnostic_schedules * spec.diagnostic_samples * len(diag_steps)
    out = {
        "periodic_steps_expected": periodic_steps(spec),
        "periodic_and_final_missing": missing,
        "diagnostic_steps_expected": diag_steps,
        "diagnostic_tasks": diag_tasks,
        "diagnostic_missing": diag_missing,
        "training_groups_expected": expected_groups,
        "training_groups_found": len(groups),
        "training_rollouts_expected": expected_rollouts,
        "training_rollouts_found": training_rollouts,
        "episodes_expected": (
            sum(sizes["periodic"].values()) * len(periodic_steps(spec))
            + (0 if spec.train_only else sum(sizes["final"].values()))
            + expected_diag
            + expected_rollouts
        ),
        "episodes_found": len(records),
    }
    out["complete"] = (
        not missing and not diag_missing and len(groups) == expected_groups and training_rollouts == expected_rollouts
    )
    return out


def luck_by_phase_strict(records: list[dict], spec: RunSpec) -> dict:
    """Luck share per diagnostic phase with the K x M cardinality enforced per task; a phase whose tables are not
    all K x M is reported with its defect rather than silently averaged."""
    out = luck_by_phase(records)
    for phase in out:
        phase_records = [r for r in records if r.get("condition") == "diag" and r.get("phase") == phase]
        try:
            luck_share_tables_by_phase(phase_records, schedules=spec.diagnostic_schedules, samples=spec.diagnostic_samples)
        except ValueError as e:
            out[phase]["defect"] = str(e)
    return out


def checkpoint_inventory(run_dir, spec: RunSpec) -> dict | None:
    """Which trainer checkpoints exist and are complete, when the weights were collected (None otherwise)."""
    from pairedrl.ops.job import list_checkpoints

    trainer = pathlib.Path(run_dir) / "trainer"
    if not trainer.exists():
        return None
    complete, incomplete = list_checkpoints(trainer)
    expected = [] if spec.eval_only else list(range(spec.checkpoint_steps, spec.steps + 1, spec.checkpoint_steps))
    found = [int(c.name.split("-")[1]) for c in complete]
    return {
        "expected": expected,
        "complete": found,
        "incomplete": [c.name for c in incomplete],
        "missing": [s for s in expected if s not in found],
        "adapter_final": (pathlib.Path(run_dir) / "adapter_final" / "adapter_model.safetensors").exists(),
    }


def run_register(run_dir, threshold: float | None = None) -> dict:
    """Everything the paper reads from one run: spec facts, periodic curves with areas, final sets, luck share
    per checkpoint, training-group totals, training curve, timing summary, the attempt lineage and completeness."""
    run_dir = pathlib.Path(run_dir)
    attempts = load_attempts(run_dir)
    manifest = attempts[-1]["manifest"]
    records, episode_lineage = lineage_records(attempts, "episodes.jsonl")
    groups, group_lineage = lineage_records(attempts, "groups.jsonl")
    spec = manifest["spec"]
    run_spec = RunSpec.from_dict(spec)
    curves = {name: periodic_curve(records, name) for name in PERIODIC_SETS}
    luck = luck_by_phase_strict(records, run_spec)
    entry = {
        "run_id": manifest["run_id"],
        "provider": manifest.get("provider", "modal"),
        "status": manifest.get("status"),
        "attempt": manifest.get("attempt"),
        "attempts": [
            {
                "attempt": a["manifest"].get("attempt"), "status": a["manifest"].get("status"),
                "git_commit": a["manifest"].get("git_commit"), "resumed_from_step": _resume_step(a["manifest"]),
                "wall_time_s": a["manifest"].get("wall_time_s"), "estimated_cost_usd": a["manifest"].get("estimated_cost_usd"),
                "error": a["manifest"].get("error"),
            }
            for a in attempts
        ],
        "total_wall_time_s": sum((a["manifest"].get("wall_time_s") or 0) for a in attempts),
        "total_estimated_cost_usd": round(sum((a["manifest"].get("estimated_cost_usd") or 0) for a in attempts), 2),
        "lineage": {"episodes": episode_lineage["attempts"], "groups": group_lineage["attempts"]},
        "git_commit": manifest.get("git_commit"),
        "condition": spec.get("condition"),
        "arm": spec.get("arm"),
        "seed": spec.get("seed"),
        "p": spec.get("p"),
        "q": spec.get("q"),
        "fault_weights": spec.get("fault_weights"),
        "steps": spec.get("steps"),
        "prompts_per_step": spec.get("prompts_per_step"),
        "num_generations": spec.get("num_generations"),
        "scale_rewards": spec.get("scale_rewards"),
        "loss_type": spec.get("loss_type"),
        "wall_time_s": manifest.get("wall_time_s"),
        "estimated_cost_usd": manifest.get("estimated_cost_usd"),
        "peak_mem_gb": manifest.get("peak_mem_gb"),
        "versions": manifest.get("versions"),
        "episodes": len(records),
        "curves": curves,
        "auc": {name: area_under_curve(points) for name, points in curves.items()},
        "final": final_sets(records),
        "luck_share": luck,
        "training_groups": summarize_groups(groups) if groups else {},
        "training_curve": training_curve(records),
        "timing": step_timing_summary(manifest.get("step_timings", [])),
        "eval_timings": manifest.get("eval_timings", []),
        "completeness": completeness(run_spec, records, groups, curves, luck),
        "checkpoints": checkpoint_inventory(run_dir, run_spec),
    }
    if threshold is not None:
        entry["threshold"] = threshold
        entry["steps_to_threshold"] = steps_to_threshold(curves["noisy"], threshold) if curves["noisy"] else None
    return entry


def format_run(entry: dict) -> str:
    lines = [
        (
            f"{entry['run_id']} ({entry['condition']} {entry['arm']} seed {entry['seed']}, {entry['provider']}): "
            f"status {entry['status']}, {entry['episodes']} episodes, {entry['wall_time_s']} s, "
            f"est {entry['estimated_cost_usd']} USD"
        )
    ]
    for name in PERIODIC_SETS:
        points = entry["curves"].get(name, [])
        if points:
            values = " ".join(f"{p['step']}:{p['true_success']:.3f}" for p in points)
            auc = entry["auc"].get(name)
            lines.append(f"  {name:10s} {values}  auc={auc:.3f}" if auc is not None else f"  {name:10s} {values}")
    for name, agg in sorted(entry["final"].items()):
        rec = agg["recovery_success"]
        lines.append(
            f"  final {name:14s} true={agg['true_success']:.3f} recovery={'n/a' if rec is None else f'{rec:.3f}'} "
            f"exposed={agg['exposed_frac']:.2f} calls={agg['mean_calls']:.1f} budget_exceeded={agg['budget_exceeded_frac']:.2f}"
        )
    for phase, luck in sorted(entry["luck_share"].items(), key=lambda kv: _phase_step(kv[0]) or 0):
        lam, pooled = luck.get("lam"), luck.get("lam_pooled")
        lines.append(
            f"  luck share {phase}: lam={'n/a' if lam is None else f'{lam:.3f}'} "
            f"pooled={'n/a' if pooled is None else f'{pooled:.3f}'} over {luck.get('tasks_defined')} of {luck.get('tasks')} tasks"
        )
    for condition, g in sorted(entry["training_groups"].items()):
        spurious = g["spurious_among_all_correct"]
        lines.append(
            f"  groups {condition}: {g['groups']} groups, zero-variance {g['zero_variance_frac']:.3f}, "
            f"all-correct {g['all_correct_groups']}, spurious among all-correct "
            f"{'n/a' if spurious is None else f'{spurious:.3f}'}"
        )
    timing = entry.get("timing") or {}
    if timing:
        gen, passes = timing.get("mean_generation_s"), timing.get("mean_passes_s")
        lines.append(
            f"  timing: {timing['steps']} steps, mean {timing['mean_step_s']:.1f} s "
            f"(generation {'n/a' if gen is None else f'{gen:.1f}'} s, passes {'n/a' if passes is None else f'{passes:.1f}'} s)"
        )
    if "threshold" in entry:
        stt = entry["steps_to_threshold"]
        lines.append(f"  threshold {entry['threshold']:.3f}: steps to threshold {'censored' if stt is None else f'{stt:.1f}'}")
    comp = entry.get("completeness") or {}
    if comp:
        lines.append(
            f"  completeness: {'COMPLETE' if comp['complete'] else 'INCOMPLETE'}; episodes {comp['episodes_found']}/{comp['episodes_expected']}, "
            f"groups {comp['training_groups_found']}/{comp['training_groups_expected']}, "
            f"missing sets {len(comp['periodic_and_final_missing'])}, diagnostic defects {len(comp['diagnostic_missing'])}; "
            f"attempts {len(entry.get('attempts', []))}, total {entry.get('total_wall_time_s')} s, est {entry.get('total_estimated_cost_usd')} USD"
        )
        for m in comp["periodic_and_final_missing"][:6]:
            lines.append(f"    missing {m['set']} step {m['step']}: {m['found']} of {m['expected']}")
        for m in comp["diagnostic_missing"][:3]:
            lines.append(f"    diagnostic {m['phase']}: {m['defect']}")
    ck = entry.get("checkpoints")
    if ck is not None:
        lines.append(
            f"  checkpoints: complete {ck['complete']}, missing {ck['missing']}, incomplete {ck['incomplete']}, "
            f"adapter_final {ck['adapter_final']}"
        )
    return "\n".join(lines)
